version: '3'

services:
  phoenix:
    image: renews/phoenix_collava:latest
    command: bash -c 'mix ecto.create; mix ecto.migrate; mix phx.server'
    depends_on:
      - rethink_db
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DB_HOSTNAME=rethink_db
    ports:
      - "4000:4000"
    links:
      - rethink_db
    volumes:
      - .:/app
  rethink_db:
    image: rethinkdb:2.3.6
    ports:
      - "29015:29015"
      - "28015:28015"
      - "8080:8080"
    volumes:
      - .:/data
